apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: monitoring-instrumentation
  namespace: otel-auto
spec:
  nodejs:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-nodejs:latest
    env:
      - name: OTEL_LOG_LEVEL
        value: info
      - name: OTEL_TRACES_EXPORTER
        value: "otlp"
      - name: OTEL_METRICS_EXPORTER
        value: "otlp"
      - name: OTEL_LOGS_EXPORTER
        value: "otlp"
  exporter:
    endpoint: http://otel-collector-collector.otel-auto.svc.cluster.local:4317
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1"
